# Generated by Django 5.0.6 on 2024-05-22 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='salary',
            field=models.CharField(default=3000, max_length=100),
            preserve_default=False,
        ),
    ]
