# Generated by Django 5.0.4 on 2024-05-23 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='salary',
            field=models.CharField(default='3000', max_length=100),
        ),
    ]
